/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceInterest = IDL.Variant({
  'seo' : IDL.Null,
  'workshop' : IDL.Null,
  'socialMediaManagement' : IDL.Null,
  'googleAds' : IDL.Null,
  'consulting' : IDL.Null,
  'paidAds' : IDL.Null,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : ServiceInterest,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceInterest],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceInterest = IDL.Variant({
    'seo' : IDL.Null,
    'workshop' : IDL.Null,
    'socialMediaManagement' : IDL.Null,
    'googleAds' : IDL.Null,
    'consulting' : IDL.Null,
    'paidAds' : IDL.Null,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : ServiceInterest,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceInterest],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };